/**
 * SimplestClaw Gateway Server
 * 
 * This server acts as a reverse proxy for OpenClaw, enabling deployment on Railway
 * and other cloud platforms that only expose a single HTTP port.
 * 
 * It handles:
 * - HTTP proxying to OpenClaw's internal port
 * - WebSocket upgrade proxying for real-time communication
 * - Health checks for Railway's deployment system
 * - Header rewriting to make connections appear local to OpenClaw
 * - Welcome page with connection instructions
 * 
 * Architecture:
 * -------------
 * [Internet] → [Railway Port] → [This Proxy :PORT] → [OpenClaw :18789]
 * 
 * Environment Variables:
 * ----------------------
 * REQUIRED (at least one API key):
 *   ANTHROPIC_API_KEY    - Anthropic Claude API key (from console.anthropic.com)
 *   OPENAI_API_KEY       - OpenAI GPT API key (from platform.openai.com)
 *   GOOGLE_API_KEY       - Google Gemini API key (from aistudio.google.com)
 *   OPENROUTER_API_KEY   - OpenRouter API key (from openrouter.ai)
 * 
 * OPTIONAL:
 *   OPENCLAW_GATEWAY_TOKEN - Gateway authentication token (auto-generated by Railway template)
 *   PORT                   - HTTP server port (default: 3000, Railway sets this automatically)
 * 
 * @see https://github.com/mbron64/simplestclaw
 * @license MIT
 */

import { spawn } from 'child_process';
import http from 'http';
import net from 'net';

// =============================================================================
// Configuration
// =============================================================================

const PORT = process.env.PORT || 3000;
const OPENCLAW_PORT = 18789;

/** List of supported API key environment variables */
const API_KEY_VARS = [
  'ANTHROPIC_API_KEY',
  'OPENAI_API_KEY',
  'GOOGLE_API_KEY',
  'OPENROUTER_API_KEY'
];

// =============================================================================
// State
// =============================================================================

let openclawHealthy = false;
let openclawProcess = null;
let hasApiKey = false;

// =============================================================================
// Environment Validation
// =============================================================================

/**
 * Validates that required environment variables are set.
 * At least one API key must be configured for OpenClaw to function.
 * 
 * @returns {boolean} True if environment is valid, false otherwise
 */
function validateEnvironment() {
  hasApiKey = API_KEY_VARS.some(key => process.env[key]);
  
  if (!hasApiKey) {
    console.error('');
    console.error('╔══════════════════════════════════════════════════════════════╗');
    console.error('║  ERROR: No API key configured                                ║');
    console.error('╠══════════════════════════════════════════════════════════════╣');
    console.error('║  Please set at least one of the following in Railway:       ║');
    console.error('║                                                              ║');
    console.error('║  • ANTHROPIC_API_KEY  (from console.anthropic.com)          ║');
    console.error('║  • OPENAI_API_KEY     (from platform.openai.com)            ║');
    console.error('║  • GOOGLE_API_KEY     (from aistudio.google.com)            ║');
    console.error('║  • OPENROUTER_API_KEY (from openrouter.ai)                  ║');
    console.error('║                                                              ║');
    console.error('║  Go to: Railway Dashboard → Your Project → Variables        ║');
    console.error('╚══════════════════════════════════════════════════════════════╝');
    console.error('');
    return false;
  }
  
  // Log which providers are configured
  const configuredProviders = API_KEY_VARS
    .filter(key => process.env[key])
    .map(key => key.replace('_API_KEY', '').toLowerCase());
  
  console.log(`API keys configured: ${configuredProviders.join(', ')}`);
  
  return true;
}

// =============================================================================
// Welcome Page
// =============================================================================

/**
 * Generates the welcome/status HTML page shown at the root URL.
 * Provides connection instructions and current gateway status.
 * 
 * @param {string} gatewayHost - The public hostname of the gateway
 * @returns {string} HTML page content
 */
function getWelcomePage(gatewayHost) {
  const wsUrl = `wss://${gatewayHost}`;
  const token = process.env.OPENCLAW_GATEWAY_TOKEN || null;
  
  // Determine status
  let statusClass, statusText, statusDetails;
  
  if (!hasApiKey) {
    statusClass = 'error';
    statusText = 'Missing API Key';
    statusDetails = `
      <p>No API key is configured. Add one in Railway Dashboard → Variables:</p>
      <ul>
        <li><code>ANTHROPIC_API_KEY</code> - from <a href="https://console.anthropic.com" target="_blank">console.anthropic.com</a></li>
        <li><code>OPENAI_API_KEY</code> - from <a href="https://platform.openai.com" target="_blank">platform.openai.com</a></li>
        <li><code>GOOGLE_API_KEY</code> - from <a href="https://aistudio.google.com" target="_blank">aistudio.google.com</a></li>
        <li><code>OPENROUTER_API_KEY</code> - from <a href="https://openrouter.ai" target="_blank">openrouter.ai</a></li>
      </ul>
      <p>After adding the variable, Railway will automatically redeploy.</p>
    `;
  } else if (!openclawHealthy) {
    statusClass = 'warning';
    statusText = 'Starting...';
    statusDetails = '<p>OpenClaw is starting up. Please wait a moment and refresh this page.</p>';
  } else {
    statusClass = 'ok';
    statusText = 'Ready';
    const tokenDisplay = token 
      ? `<code id="token" class="token">${token}</code>
         <button onclick="navigator.clipboard.writeText('${token}'); this.textContent='Copied!'; setTimeout(() => this.textContent='Copy', 2000)" class="copy-btn">Copy</button>`
      : '<span class="warning-text">Not configured</span>';
    statusDetails = `
      <h2>Connect to OpenClaw</h2>
      <table>
        <tr><td><strong>WebSocket URL</strong></td><td><code>${wsUrl}</code></td></tr>
        <tr><td><strong>Gateway Token</strong></td><td>${tokenDisplay}</td></tr>
      </table>
      <p>Copy the token above, then paste it in the Control UI settings.</p>
      <a class="button" href="/__openclaw__/control/#/overview" target="_blank">Open Control UI Settings</a>
    `;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SimplestClaw Gateway</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 700px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #0a0a0a;
      color: #e5e5e5;
      line-height: 1.6;
    }
    h1 { 
      font-size: 2rem; 
      margin-bottom: 0.5rem;
      color: #fff;
    }
    h2 { 
      font-size: 1.25rem; 
      margin-top: 2rem;
      color: #fff;
    }
    .subtitle {
      color: #888;
      margin-bottom: 2rem;
    }
    .status {
      padding: 16px 20px;
      border-radius: 8px;
      margin: 24px 0;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .status::before {
      content: '';
      width: 12px;
      height: 12px;
      border-radius: 50%;
      flex-shrink: 0;
    }
    .status.ok { background: rgba(34, 197, 94, 0.1); border: 1px solid rgba(34, 197, 94, 0.3); }
    .status.ok::before { background: #22c55e; }
    .status.warning { background: rgba(234, 179, 8, 0.1); border: 1px solid rgba(234, 179, 8, 0.3); }
    .status.warning::before { background: #eab308; }
    .status.error { background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.3); }
    .status.error::before { background: #ef4444; }
    code {
      background: #1a1a1a;
      padding: 3px 8px;
      border-radius: 4px;
      font-family: 'SF Mono', Monaco, monospace;
      font-size: 0.9em;
      border: 1px solid #333;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
    }
    td {
      padding: 12px 0;
      border-bottom: 1px solid #222;
    }
    td:first-child { width: 140px; color: #888; }
    ul { padding-left: 20px; }
    li { margin: 8px 0; }
    a { color: #60a5fa; }
    a:hover { color: #93c5fd; }
    .button {
      display: inline-block;
      padding: 12px 24px;
      background: #fff;
      color: #000;
      text-decoration: none;
      border-radius: 8px;
      font-weight: 500;
      margin-top: 16px;
      transition: opacity 0.2s;
    }
    .button:hover { opacity: 0.9; color: #000; }
    .copy-btn {
      padding: 4px 10px;
      background: #333;
      color: #fff;
      border: 1px solid #444;
      border-radius: 4px;
      cursor: pointer;
      font-size: 0.75rem;
      margin-left: 8px;
      transition: all 0.2s;
    }
    .copy-btn:hover { background: #444; }
    .token {
      word-break: break-all;
      display: inline;
    }
    .warning-text { color: #eab308; }
    .footer {
      margin-top: 48px;
      padding-top: 24px;
      border-top: 1px solid #222;
      color: #666;
      font-size: 0.875rem;
    }
    .footer a { color: #888; }
  </style>
</head>
<body>
  <h1>SimplestClaw Gateway</h1>
  <p class="subtitle">OpenClaw hosted on Railway</p>
  
  <div class="status ${statusClass}">
    <span><strong>Status:</strong> ${statusText}</span>
  </div>
  
  ${statusDetails}
  
  <div class="footer">
    <p>
      <a href="https://github.com/mbron64/simplestclaw" target="_blank">GitHub</a> · 
      <a href="https://docs.openclaw.ai" target="_blank">OpenClaw Docs</a> · 
      <a href="/health">Health Check</a>
    </p>
  </div>
</body>
</html>`;
}

// =============================================================================
// OpenClaw Process Management
// =============================================================================

/**
 * Starts OpenClaw gateway as a child process.
 * Handles stdout/stderr logging and automatic restart on crash.
 */
function startOpenClaw() {
  console.log('Starting OpenClaw gateway...');
  
  const args = [
    'openclaw', 'gateway',
    '--port', String(OPENCLAW_PORT),
    '--bind', 'lan',
    '--allow-unconfigured'
  ];

  // Add token if configured (auto-generated by Railway template)
  if (process.env.OPENCLAW_GATEWAY_TOKEN) {
    args.push('--token', process.env.OPENCLAW_GATEWAY_TOKEN);
  }

  openclawProcess = spawn('npx', args, {
    stdio: ['ignore', 'pipe', 'pipe'],
    env: {
      ...process.env,
      // Increase Node heap size to prevent OOM crashes (Railway Hobby has 8GB limit)
      NODE_OPTIONS: '--max-old-space-size=2048',
      // Pass through API keys for supported providers
      ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
      OPENAI_API_KEY: process.env.OPENAI_API_KEY,
      GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
      OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
    }
  });

  openclawProcess.stdout.on('data', (data) => {
    console.log(`[openclaw] ${data.toString().trim()}`);
    // Mark healthy when gateway starts listening
    if (data.toString().includes('listening') || data.toString().includes('started')) {
      openclawHealthy = true;
    }
  });

  openclawProcess.stderr.on('data', (data) => {
    console.error(`[openclaw] ${data.toString().trim()}`);
  });

  openclawProcess.on('close', (code) => {
    console.log(`OpenClaw exited with code ${code}`);
    openclawHealthy = false;
    // Restart after delay (handles crashes gracefully)
    setTimeout(startOpenClaw, 5000);
  });

  // Mark healthy after startup delay (fallback if log detection fails)
  setTimeout(() => {
    openclawHealthy = true;
  }, 5000);
}

// =============================================================================
// HTTP Proxy
// =============================================================================

/**
 * Filters out proxy-related headers so OpenClaw treats connections as local.
 * This prevents "pairing required" errors when behind a reverse proxy.
 * 
 * @param {Object} headers - Original request headers
 * @returns {Object} Filtered headers
 */
function filterProxyHeaders(headers) {
  const filtered = {};
  for (const [key, value] of Object.entries(headers)) {
    const lowerKey = key.toLowerCase();
    if (!lowerKey.startsWith('x-forwarded') && 
        !lowerKey.startsWith('x-real') &&
        lowerKey !== 'forwarded') {
      filtered[key] = value;
    }
  }
  return filtered;
}

/**
 * Proxies an HTTP request to OpenClaw's internal port.
 * 
 * @param {http.IncomingMessage} req - Incoming request
 * @param {http.ServerResponse} res - Outgoing response
 */
function proxyRequest(req, res) {
  const options = {
    hostname: 'localhost',
    port: OPENCLAW_PORT,
    path: req.url,
    method: req.method,
    headers: {
      ...filterProxyHeaders(req.headers),
      host: `localhost:${OPENCLAW_PORT}`
    }
  };

  const proxyReq = http.request(options, (proxyRes) => {
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res);
  });

  proxyReq.on('error', (err) => {
    console.error(`Proxy error: ${err.message}`);
    res.writeHead(502, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Bad Gateway', message: 'OpenClaw not available' }));
  });

  req.pipe(proxyReq);
}

// =============================================================================
// HTTP Server
// =============================================================================

const server = http.createServer((req, res) => {
  // Health check endpoint for Railway
  if (req.url === '/health') {
    if (openclawHealthy && hasApiKey) {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ 
        status: 'ok', 
        openclaw: 'running',
        wsPort: OPENCLAW_PORT 
      }));
    } else {
      res.writeHead(503, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ 
        status: hasApiKey ? 'starting' : 'misconfigured',
        error: hasApiKey ? null : 'No API key configured'
      }));
    }
    return;
  }

  // Welcome page at root
  if (req.url === '/' && req.method === 'GET') {
    const host = req.headers.host || 'localhost';
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(getWelcomePage(host));
    return;
  }

  // Proxy all other requests to OpenClaw
  proxyRequest(req, res);
});

// =============================================================================
// WebSocket Proxy
// =============================================================================

/**
 * Handles WebSocket upgrade requests by proxying to OpenClaw.
 * Rewrites headers to make the connection appear local.
 */
server.on('upgrade', (req, socket, head) => {
  const proxySocket = net.connect(OPENCLAW_PORT, 'localhost', () => {
    // Rewrite headers to make connection appear local to OpenClaw
    const rewrittenHeaders = Object.entries(req.headers)
      .filter(([key]) => {
        const lowerKey = key.toLowerCase();
        return !lowerKey.startsWith('x-forwarded') && 
               !lowerKey.startsWith('x-real') &&
               lowerKey !== 'forwarded';
      })
      .map(([key, value]) => {
        const lowerKey = key.toLowerCase();
        if (lowerKey === 'host') {
          return `${key}: localhost:${OPENCLAW_PORT}`;
        }
        if (lowerKey === 'origin') {
          return `${key}: http://localhost:${OPENCLAW_PORT}`;
        }
        return `${key}: ${value}`;
      })
      .join('\r\n');
    
    const upgradeRequest = [
      `${req.method} ${req.url} HTTP/1.1`,
      rewrittenHeaders,
      '',
      ''
    ].join('\r\n');

    proxySocket.write(upgradeRequest);
    
    if (head && head.length > 0) {
      proxySocket.write(head);
    }

    socket.pipe(proxySocket);
    proxySocket.pipe(socket);
  });

  proxySocket.on('error', (err) => {
    console.error(`WebSocket proxy error: ${err.message}`);
    socket.end();
  });

  socket.on('error', (err) => {
    console.error(`Client socket error: ${err.message}`);
    proxySocket.end();
  });
});

// =============================================================================
// Graceful Shutdown
// =============================================================================

process.on('SIGTERM', () => {
  console.log('Received SIGTERM, shutting down...');
  if (openclawProcess) {
    openclawProcess.kill('SIGTERM');
  }
  server.close(() => process.exit(0));
});

process.on('SIGINT', () => {
  console.log('Received SIGINT, shutting down...');
  if (openclawProcess) {
    openclawProcess.kill('SIGTERM');
  }
  server.close(() => process.exit(0));
});

// =============================================================================
// Startup
// =============================================================================

console.log('');
console.log('╔══════════════════════════════════════════════════════════════╗');
console.log('║  SimplestClaw Gateway                                        ║');
console.log('║  OpenClaw hosted on Railway                                  ║');
console.log('╚══════════════════════════════════════════════════════════════╝');
console.log('');

// Validate environment (continues even if invalid, shows error page)
validateEnvironment();

// Start OpenClaw (even without API key, so user sees helpful error)
startOpenClaw();

// Start HTTP server
server.listen(PORT, '0.0.0.0', () => {
  console.log('');
  console.log(`Proxy server listening on port ${PORT}`);
  console.log(`OpenClaw gateway running on internal port ${OPENCLAW_PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
  console.log(`Welcome page: http://localhost:${PORT}/`);
  console.log('');
});
